[window]
padding.x = 20
padding.y = 20

[font]
normal.family = "Iosevka Nerd Font"
size = 17
glyph_offset.x = 0
glyph_offset.y = 0

[colors]
primary.background = "#0e0a02"
primary.foreground = "#bfc9db"
cursor.text = "CellForeground"
cursor.cursor = "#bfc9db"

[colors.normal]
black = "#646a73"
blue = "#5eb7ff"
cyan = "#4ac2b8"
green = "#87c05f"
magenta = "#dd97f1"
red = "#ff838b"
white = "#adb0bb"
yellow = "#eb8332"

[colors.bright]
black = "#646a73"
blue = "#5eb7ff"
cyan = "#4ac2b8"
green = "#87c05f"
magenta = "#dd97f1"
red = "#ff838b"
white = "#696c76"
yellow = "#f5983a"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
